#!/bin/bash
#echo "Processing files in zip folder $1"
echo "<HTML>"
echo "<HEAD>"
echo "<TITLE>DataPower-MQQM Report</TITLE>"
echo "<STYLE>"
echo "table, th, td {"
echo "        border: 1px solid black;"
echo "}"
echo 
echo "th, td {"
echo "        padding: 10px;"
echo "}"
echo "</STYLE>"
echo "</HEAD>"
echo "<BODY>"

for zipfile in $1/*.zip; do

	echo "<BR>DataPower Export $zipfile<BR>"
	echo "<TABLE>"
	echo "<TR STYLE='background-color:#888888;color:#FFFFFF'><TH>DOMAIN</TH><TH>QMANAGER</TH><TH>RETRY INTERVAL</TH><TH>RETRY ATTEMPTS</TH></TR>"

	zipdir=$(basename -s .zip $zipfile)
	unzip -jo $zipfile '*.zip' -d ./$zipdir > /dev/null
	for exportfile in $zipdir/*.zip; do
		exportxml=$(unzip -p $exportfile export.xml)
		domain=$(echo $exportxml | grep -o -P '(?<=domain\=").*(?=\")' | sed 's/".*//')

		echo $exportxml | grep -o -P '(?<=<MQQM)(?s).*(?=</MQQM>)' | while read -r qm; do
				qmname=$(echo $qm | grep -o -P '(?<=name\=").*(?=\")' | sed 's/".*//')
				retryinterval=$(echo $qm | grep -o -P '(?<=<RetryInterval>)(?s).*(?=</RetryInterval>)')
				retryattempts=$(echo $qm | grep -o -P '(?<=<RetryAttempts>)(?s).*(?=</RetryAttempts>)')
				if (( $retryinterval < 90 )) || (( $retryattempts < 30 )); then
				echo "<TR STYLE='text-align:center'><TD>$domain</TD><TD>$qmname</TD>"
				if (( $retryinterval < 90 )); then
					echo "<TD STYLE='color:#FF0000'>$retryinterval</TD>"
				else
					echo "<TD STYLE='color:#000000'>$retryinterval</TD>"
				fi
				if (( $retryattempts < 30 )); then
					echo "<TD STYLE='color:#FF0000'>$retryattempts</TD>"
				else
					echo "<TD STYLE='color:#000000'>$retryattempts</TD>"
				fi
				echo "</TR>"
				fi
			   done
	done
	echo "</TABLE><BR><BR>"
done
echo "</BODY>"
echo "</HTML>"

